### ISSUE TITLE
Strange issue with handlebars loader

### ISSUE THREAD

**Issue by craigmulligan** [craig-mulligan/doxxWebpack#1]
Getting some weird behaviour when trying to export an object from `handlebars-loader` instead on a function. 

Some context: we first need to run each `.md` file through `frontmatter-loader` which returns an object, we then pass it to handle-bars loader and precompile the template. We then pass it to `static.js` to load the context data and create all the paths for templates. It all seems to be working fine, except partials are not rendered (they are appear uncompiled as `[object]`). 

Interestingly if you pass just the template function back to `static.js` it works fine, and renders all partials. :/

Code in question is [here](https://github.com/craig-mulligan/handlebars-loader/blob/master/index.js#L322)

but basically

This works
```
module.exports = handlebars.template(templateSpec)
```

This doesn't 
```
module.exports = () => {
 compile: handlebars.template(templateSpec),
 attributes: myFrontMatterData
}
```

Interestingly this throws a handlebars error `ERROR in Error: The partial myPartial could not be compiled when running in runtime-only mode`. 
```
module.exports = {
 compile: handlebars.template(templateSpec),
 attributes: myFrontMatterData
}
```

Must have something to do with the [webpack module api](https://github.com/webpack/docs/wiki/api-in-modules) but not sure..

Any help appreciated 👍

**Comment by emirotin** [comment]
I don't have any experience creating webpack modules / loaders.
The only difference I see here is that with the function you _delay_ the template compilation — it's now happening only when the function is _executed_, not when it's exported.

An example equivalent to your original attempt would be:

```
const template = handlebars.template(templateSpec)

module.exports = () => {
 compile: template,
 attributes: myFrontMatterData
}
```

**Comment by craigmulligan** [comment]
Tried it, same results. So weird.
